all:exemplesbrk exemplemalloc exemplefree exemplefree2
exemplesbrk:exemplesbrk.c
	 gcc -o exemplesbrk exemplesbrk.c
exemplemalloc:exemplemalloc.c
	gcc -o exemplemalloc exemplemalloc.c 
exemplefree:exemplefree.c
	gcc -o exemplefree exemplefree.c 
exemplefree2:exemplefree2.c
	gcc -o exemplefree2 exemplefree2.c 
clean:
	rm -f exemplesbrk exemplemalloc exemplefree exemplefree2

